//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenXe()
        {
            this.PhanCongs = new HashSet<PhanCong>();
        }
    
        public int IDChuyen { get; set; }
        public Nullable<int> GiaVe { get; set; }
        public Nullable<int> IDBenXeDi { get; set; }
        public Nullable<int> IDBenXeVe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
        public virtual BenXeDi BenXeDi { get; set; }
        public virtual BenXeVe BenXeVe { get; set; }
    }
}
