//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyBenXeEntities : DbContext
    {
        public QuanLyBenXeEntities()
            : base("name=QuanLyBenXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenXe> ChuyenXes { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NhaXe> NhaXes { get; set; }
        public virtual DbSet<PhanCong> PhanCongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<BenXeDi> BenXeDis { get; set; }
        public virtual DbSet<BenXeVe> BenXeVes { get; set; }
    
        public virtual ObjectResult<string> spTrung(string diaDiem)
        {
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spTrung", diaDiemParameter);
        }
    
        public virtual int spdeleteBenXe(Nullable<int> iDBenXe)
        {
            var iDBenXeParameter = iDBenXe.HasValue ?
                new ObjectParameter("IDBenXe", iDBenXe) :
                new ObjectParameter("IDBenXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spdeleteBenXe", iDBenXeParameter);
        }
    }
}
