//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBX.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyBenXeEntities : DbContext
    {
        public QuanLyBenXeEntities()
            : base("name=QuanLyBenXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenXeDi> BenXeDis { get; set; }
        public virtual DbSet<BenXeVe> BenXeVes { get; set; }
        public virtual DbSet<ChuyenXe> ChuyenXes { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<PhanCong> PhanCongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<NhaXe> NhaXes { get; set; }
    
        public virtual int deleteghe(Nullable<int> iDXe, string ngayKH)
        {
            var iDXeParameter = iDXe.HasValue ?
                new ObjectParameter("IDXe", iDXe) :
                new ObjectParameter("IDXe", typeof(int));
    
            var ngayKHParameter = ngayKH != null ?
                new ObjectParameter("NgayKH", ngayKH) :
                new ObjectParameter("NgayKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteghe", iDXeParameter, ngayKHParameter);
        }
    
        public virtual int deletephancong(Nullable<int> iDXe, string ngayKH, Nullable<int> iDChuyen)
        {
            var iDXeParameter = iDXe.HasValue ?
                new ObjectParameter("IDXe", iDXe) :
                new ObjectParameter("IDXe", typeof(int));
    
            var ngayKHParameter = ngayKH != null ?
                new ObjectParameter("NgayKH", ngayKH) :
                new ObjectParameter("NgayKH", typeof(string));
    
            var iDChuyenParameter = iDChuyen.HasValue ?
                new ObjectParameter("IDChuyen", iDChuyen) :
                new ObjectParameter("IDChuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletephancong", iDXeParameter, ngayKHParameter, iDChuyenParameter);
        }
    
        public virtual int editghe(Nullable<int> iDXe, string ngayKH, Nullable<System.DateTime> ngayEdit)
        {
            var iDXeParameter = iDXe.HasValue ?
                new ObjectParameter("IDXe", iDXe) :
                new ObjectParameter("IDXe", typeof(int));
    
            var ngayKHParameter = ngayKH != null ?
                new ObjectParameter("NgayKH", ngayKH) :
                new ObjectParameter("NgayKH", typeof(string));
    
            var ngayEditParameter = ngayEdit.HasValue ?
                new ObjectParameter("NgayEdit", ngayEdit) :
                new ObjectParameter("NgayEdit", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editghe", iDXeParameter, ngayKHParameter, ngayEditParameter);
        }
    
        public virtual ObjectResult<string> getchuyenxebyghe(Nullable<int> iD, Nullable<System.DateTime> ngayKH)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var ngayKHParameter = ngayKH.HasValue ?
                new ObjectParameter("NgayKH", ngayKH) :
                new ObjectParameter("NgayKH", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getchuyenxebyghe", iDParameter, ngayKHParameter);
        }
    
        public virtual ObjectResult<getLotrinh_Result> getLotrinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLotrinh_Result>("getLotrinh");
        }
    
        public virtual ObjectResult<getLotrinhSoghe_Result> getLotrinhSoghe(Nullable<int> iDXe)
        {
            var iDXeParameter = iDXe.HasValue ?
                new ObjectParameter("IDXe", iDXe) :
                new ObjectParameter("IDXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLotrinhSoghe_Result>("getLotrinhSoghe", iDXeParameter);
        }
    
        public virtual ObjectResult<getlotrinhxe_Result> getlotrinhxe(Nullable<int> iDDi, Nullable<int> iDVe, string ngayKH)
        {
            var iDDiParameter = iDDi.HasValue ?
                new ObjectParameter("IDDi", iDDi) :
                new ObjectParameter("IDDi", typeof(int));
    
            var iDVeParameter = iDVe.HasValue ?
                new ObjectParameter("IDVe", iDVe) :
                new ObjectParameter("IDVe", typeof(int));
    
            var ngayKHParameter = ngayKH != null ?
                new ObjectParameter("NgayKH", ngayKH) :
                new ObjectParameter("NgayKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getlotrinhxe_Result>("getlotrinhxe", iDDiParameter, iDVeParameter, ngayKHParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<spChitiethoadon_Result> spChitiethoadon(Nullable<int> idhoadon)
        {
            var idhoadonParameter = idhoadon.HasValue ?
                new ObjectParameter("idhoadon", idhoadon) :
                new ObjectParameter("idhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spChitiethoadon_Result>("spChitiethoadon", idhoadonParameter);
        }
    
        public virtual ObjectResult<spchuyenxe1_Result> spchuyenxe1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spchuyenxe1_Result>("spchuyenxe1");
        }
    
        public virtual int spdeleteBenXe(Nullable<int> iDBenXe)
        {
            var iDBenXeParameter = iDBenXe.HasValue ?
                new ObjectParameter("IDBenXe", iDBenXe) :
                new ObjectParameter("IDBenXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spdeleteBenXe", iDBenXeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spDemsoghedadat(Nullable<int> idhoadon)
        {
            var idhoadonParameter = idhoadon.HasValue ?
                new ObjectParameter("idhoadon", idhoadon) :
                new ObjectParameter("idhoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spDemsoghedadat", idhoadonParameter);
        }
    
        public virtual ObjectResult<spHoaDon_Result> spHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spHoaDon_Result>("spHoaDon");
        }
    
        public virtual ObjectResult<udsGetNhaXe_Result> udsGetNhaXe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<udsGetNhaXe_Result>("udsGetNhaXe");
        }
    
        public virtual ObjectResult<udsXebyIDnhaxe_Result> udsXebyIDnhaxe(Nullable<int> iDNhaXe)
        {
            var iDNhaXeParameter = iDNhaXe.HasValue ?
                new ObjectParameter("IDNhaXe", iDNhaXe) :
                new ObjectParameter("IDNhaXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<udsXebyIDnhaxe_Result>("udsXebyIDnhaxe", iDNhaXeParameter);
        }
    
        public virtual ObjectResult<udsXebyIDnhaxeandLoai_Result> udsXebyIDnhaxeandLoai(Nullable<int> iDNhaXe, string nameLoai)
        {
            var iDNhaXeParameter = iDNhaXe.HasValue ?
                new ObjectParameter("IDNhaXe", iDNhaXe) :
                new ObjectParameter("IDNhaXe", typeof(int));
    
            var nameLoaiParameter = nameLoai != null ?
                new ObjectParameter("NameLoai", nameLoai) :
                new ObjectParameter("NameLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<udsXebyIDnhaxeandLoai_Result>("udsXebyIDnhaxeandLoai", iDNhaXeParameter, nameLoaiParameter);
        }
    
        public virtual int updatephancong(Nullable<int> iDXe, string ngayKH, Nullable<int> iDChuyen, Nullable<System.DateTime> ngayKHed, Nullable<int> iDChuyened, Nullable<System.DateTime> thoiGianDen)
        {
            var iDXeParameter = iDXe.HasValue ?
                new ObjectParameter("IDXe", iDXe) :
                new ObjectParameter("IDXe", typeof(int));
    
            var ngayKHParameter = ngayKH != null ?
                new ObjectParameter("NgayKH", ngayKH) :
                new ObjectParameter("NgayKH", typeof(string));
    
            var iDChuyenParameter = iDChuyen.HasValue ?
                new ObjectParameter("IDChuyen", iDChuyen) :
                new ObjectParameter("IDChuyen", typeof(int));
    
            var ngayKHedParameter = ngayKHed.HasValue ?
                new ObjectParameter("NgayKHed", ngayKHed) :
                new ObjectParameter("NgayKHed", typeof(System.DateTime));
    
            var iDChuyenedParameter = iDChuyened.HasValue ?
                new ObjectParameter("IDChuyened", iDChuyened) :
                new ObjectParameter("IDChuyened", typeof(int));
    
            var thoiGianDenParameter = thoiGianDen.HasValue ?
                new ObjectParameter("ThoiGianDen", thoiGianDen) :
                new ObjectParameter("ThoiGianDen", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatephancong", iDXeParameter, ngayKHParameter, iDChuyenParameter, ngayKHedParameter, iDChuyenedParameter, thoiGianDenParameter);
        }
    
        public virtual int spXoaChuyenXe(Nullable<int> idChuyenXe)
        {
            var idChuyenXeParameter = idChuyenXe.HasValue ?
                new ObjectParameter("idChuyenXe", idChuyenXe) :
                new ObjectParameter("idChuyenXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaChuyenXe", idChuyenXeParameter);
        }
    
        public virtual int insertnhaxe(string name, Nullable<int> sDT)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertnhaxe", nameParameter, sDTParameter);
        }
    
        public virtual int insertchuyenxe(Nullable<int> idBenDi, Nullable<int> idBenVe, Nullable<int> giaVe)
        {
            var idBenDiParameter = idBenDi.HasValue ?
                new ObjectParameter("idBenDi", idBenDi) :
                new ObjectParameter("idBenDi", typeof(int));
    
            var idBenVeParameter = idBenVe.HasValue ?
                new ObjectParameter("idBenVe", idBenVe) :
                new ObjectParameter("idBenVe", typeof(int));
    
            var giaVeParameter = giaVe.HasValue ?
                new ObjectParameter("GiaVe", giaVe) :
                new ObjectParameter("GiaVe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertchuyenxe", idBenDiParameter, idBenVeParameter, giaVeParameter);
        }
    
        public virtual int spDangKy(string taiKhoan, string matKhau)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDangKy", taiKhoanParameter, matKhauParameter);
        }
    
        [DbFunction("QuanLyBenXeEntities", "fcLayGhe")]
        public virtual IQueryable<fcLayGhe_Result> fcLayGhe(Nullable<int> mahoadon)
        {
            var mahoadonParameter = mahoadon.HasValue ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fcLayGhe_Result>("[QuanLyBenXeEntities].[fcLayGhe](@mahoadon)", mahoadonParameter);
        }
    
        public virtual int deletenhaxe(Nullable<int> idnhaXe)
        {
            var idnhaXeParameter = idnhaXe.HasValue ?
                new ObjectParameter("idnhaXe", idnhaXe) :
                new ObjectParameter("idnhaXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletenhaxe", idnhaXeParameter);
        }
    
        public virtual int spXoaXe(Nullable<int> idXe)
        {
            var idXeParameter = idXe.HasValue ?
                new ObjectParameter("idXe", idXe) :
                new ObjectParameter("idXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaXe", idXeParameter);
        }
    }
}
